import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import electron from 'vite-plugin-electron'
import electronRenderer from 'vite-plugin-electron-renderer'
import path from 'path'
import fs from 'fs'

function fixPreloadCjsFile() {
  const cjs = path.resolve(__dirname, 'dist-electron/preload.cjs')
  if (!fs.existsSync(cjs)) return

  let content = fs.readFileSync(cjs, 'utf-8')
  let changed = false
  const appendBootstrapCall = (variableName: string) => {
    const callSnippet = `\n${variableName}();\n`
    if (!content.includes(callSnippet.trim())) {
      content = `${content.trimEnd()}${callSnippet}`
      changed = true
      console.log(`[fix-preload-cjs] Appended bootstrap call for ${variableName}`)
    }
  }

  if (content.includes('export default')) {
    // Remove stray ESM export generated by bundling so Electron can load as CJS.
    content = content.replace(/export\s+default\s+([^\n;]+)\s*;?/m, '$1')
    changed = true
    console.log('[fix-preload-cjs] Removed export default from preload.cjs')
  }

  // Some builds wrap preload body in a lazy function but never execute it.
  if (content.includes('var a = g(() => {') && !content.includes('\na();')) {
    content = `${content.trimEnd()}\n\na();\n`
    changed = true
    console.log('[fix-preload-cjs] Appended preload bootstrap call')
  }

  const bootstrapWrapperMatch = content.match(/var\s+([A-Za-z_$][\w$]*)\s*=\s*[A-Za-z_$][\w$]*\(\(\)\s*=>\s*\{/)
  if (bootstrapWrapperMatch) {
    appendBootstrapCall(bootstrapWrapperMatch[1])
  }

  if (changed) {
    fs.writeFileSync(cjs, content, 'utf-8')
  }
}

export default defineConfig({
  plugins: [
    react(),
    electron([
      {
        entry: 'electron/main.ts',
        vite: {
          build: {
            outDir: 'dist-electron',
            rollupOptions: {
              external: ['electron'],
            },
          }
        }
      },
      {
        entry: 'electron/preload.ts',
        onstart(options) {
          options.reload()
        },
        vite: {
          build: {
            outDir: 'dist-electron',
            rollupOptions: {
              external: ['electron'],
              output: {
                format: 'cjs',
                entryFileNames: 'preload.cjs',
              },
            },
          }
        }
      }
    ]),
    electronRenderer(),
    // Fix preload in both build and watch/dev pipelines.
    {
      name: 'fix-preload-cjs',
      writeBundle() {
        fixPreloadCjsFile()
      },
      closeBundle() {
        fixPreloadCjsFile()
      }
    }
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src')
    }
  },
  build: {
    outDir: 'dist',
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (!id.includes('node_modules')) return

          if (id.includes('reactflow')) return 'vendor-reactflow'
          if (id.includes('react-markdown') || id.includes('remark') || id.includes('rehype') || id.includes('highlight')) {
            return 'vendor-markdown'
          }
          if (id.includes('react-router') || id.includes('@remix-run')) return 'vendor-router'
          if (id.includes('react') || id.includes('scheduler')) return 'vendor-react'
        },
      },
    },
  }
})
